# action.yml
name: 'Cargo ChecktCT'
description: 'Run cargo-checkct'
inputs:
  directory: # Target workspace
    description: 'path to the target workspace (containing the checkct directory)'
    required: true
  binsec-version:  # Binsec version to use
    description: 'binsec version'
    required: false
    default: 'latest'
  unisim-version:  # Unisim_archisec version to use
    description: 'unisim_archisec version'
    required: false
    default: 'latest'
  skip-unknown: # Don't fail if binsec result status is unknown
    description: 'do not raise an error if binsec cannot conclude on the tested implementation'
    required: false
    default: 'false'
  timeout: # Timeout
    description: 'cargo-checktct timeout in seconds'
    required: false
    default: '600'

runs:
  using: "composite"
  steps:
    - name: Install Binsec
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libgmp-dev gcc g++ opam

        opam init -y
        opam install -y dune dune-site menhir grain_dypgen ocamlgraph zarith toml bitwuzla
        eval $(opam env)

        git clone https://github.com/binsec/binsec
        git clone https://github.com/binsec/unisim_archisec

        pushd binsec
        if  [[ $BINSEC_VERSION == "latest" ]]; then
          git checkout --quiet $(git describe --tags `git rev-list --tags --max-count=1`)
        else
          git checkout --quiet $BINSEC_VERSION
        fi
        dune build @install && dune install
        popd

        pushd unisim_archisec
        if  [[ $UNISIM_VERSION == "latest" ]]; then
          git checkout --quiet $(git describe --tags `git rev-list --tags --max-count=1`)
        else
          git checkout --quiet $UNISIM_VERSION
        fi
        dune build @install && dune install
        popd
      env:
        BINSEC_VERSION: ${{ inputs.binsec_version }}
        UNISIM_VERSION: ${{ inputs.unisim_version }}

    - name: Install cargo-checkct
      run: |
        git clone -b "fix/stack_protector" https://github.com/Ledger-Donjon/cargo-checkct
        cd cargo-checkct
        cargo b --release
      shell: bash

    - name: Run cargo-checkct
      run: |
        eval $(opam env)
        if [[ "$SKIP_UNKNOWN" == "true" ]]; then
          ./cargo-checkct/target/release/cargo-checkct run -d "$DIRECTORY" -t "$TIMEOUT" --skip_unknown
        else
          ./cargo-checkct/target/release/cargo-checkct run -d "$DIRECTORY" -t "$TIMEOUT"
        fi
      shell: bash
      env:
        DIRECTORY: ${{ inputs.directory }}
        TIMEOUT: ${{ inputs.timeout }}
        SKIP_UNKNOWN: ${{ inputs.skip_unknown }}
